artifactory:
  image: nginx:1.12.2-alpine
  volumes:
    - /Users/yyovkov-c/Projects/FileShare:/usr/share/nginx/html:ro
  ports:
    - 8080:80

fileserver:
  image: blabla:latest
  volumes:
    - /Users/yyovkov-c/Projects/FileShare/winshare:/winshare:ro
  tty: true
  ports:
    - 139:139
    - 445:445

    