version: '2'

networks:
  graylog.net:

services:
  mongo:
    image: ${IMAGE_MONGO}
    volumes:
      - ${VOLUME_DIR}/mongo:/data/db
    networks:
      - graylog.net

  elasticsearch:
    image: ${IMAGE_ELASTICSEARCH}
    volumes:
      - ${VOLUME_DIR}/es_data:/usr/share/elasticsearch/data
    env_file:
      - ./env_es
    networks:
       - graylog.net
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  graylog:
    image: ${IMAGE_GRAYLOG}
    volumes:
      - ${VOLUME_DIR}/graylog:/usr/share/graylog/data/journal
    env_file:
      - ./env_graylog
    links:
      - mongo
      - elasticsearch
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - graylog.net
    ports:
      - 1514:1514 # Syslog TCP
      - 1514:1514/udp # Syslog UDP
      - 12201:12201 # GELF TCP
      - 12201:12201/udp # GELF UDP

  nginx:
    image: ${IMAGE_NGINX}
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
    links:
      - graylog:graylog
    depends_on:
      - graylog
    networks:
      - graylog.net
    ports:
      - 80:80
      - 443:443
